import './globals.css'
import './styles.css'
import ShaderBackground from '@/components/ShaderBackground'
import Navbar from '@/components/Navbar'

export const metadata = {
  title: 'Jackson Halverson 2024 Portfolio',
  description: 'Generated by create next app',
  icons: {
    icon: '/JH-emblem-white.svg'
  }
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <ShaderBackground />
        <Navbar />
        {children}
      </body>
    </html>
  )
}
